L_PAREN = '('
R_PAREN = ')'

L_CURLY_BRACKET = '{'
R_CURLY_BRACKET = '}'

L_BRACKET = '['
R_BRACKET = ']'

L_ANGLE_BRACKET = '<'
R_ANGLE_BRACKET = '>'

OPENERS = {
    L_PAREN: R_PAREN, 
    L_CURLY_BRACKET: R_CURLY_BRACKET, 
    L_BRACKET: R_BRACKET, 
    L_ANGLE_BRACKET: R_ANGLE_BRACKET
}

CLOSERS = {
    R_PAREN: L_PAREN,
    R_CURLY_BRACKET: L_CURLY_BRACKET,
    R_BRACKET: L_BRACKET,
    R_ANGLE_BRACKET: L_ANGLE_BRACKET
}

COMPLETION_SCORES = {
    R_PAREN: 1,
    R_BRACKET: 2,
    R_CURLY_BRACKET: 3,
    R_ANGLE_BRACKET: 4
}